FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SRC_URI:append = " file://0001-add-aup-zu3-target.patch"

COMPATIBLE_MACHINE:zynqmp = ".*"
OPTEEMACHINE:zynqmp = "zynqmp"
EXTRA_OEMAKE:append:zynqmp = " PLATFORM_FLAVOR=aup_zu3 CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=1 CFG_DDR_SIZE=0x100000000 CFG_TZDRAM_START=0x1E001000 CFG_CORE_TXLAT_TABLES=32 MAX_XLAT_TABLES=32 CFG_CORE_RESERVED_SHM=n"
CFLAGS:append:zynqmp = " -DMAX_XLAT_TABLES=32"
